// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales = 'en' | 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * —​ ​文​字​冒​险​游​戏​ ​—
   */
  tagline: string
  /**
   * 在​一​切​改​变​前​的​4​8​小​时​。
   */
  gameSubtitle: string
  /**
   * 新​游​戏
   */
  newGame: string
  /**
   * 继​续
   */
  continue: string
  /**
   * v​0​.​1​.​0​ ​—​ ​独​立​作​品
   */
  versionLabel: string
  /**
   * 载​入​中​.​.​.
   */
  loading: string
  /**
   * 正​在​载​入​场​景​…
   */
  loadingScene: string
  /**
   * 关​闭
   */
  dismiss: string
  /**
   * 你​的​选​择
   */
  yourMove: string
  /**
   * 条​件​不​满​足
   */
  requirementsNotMet: string
  /**
   * 状​态
   */
  statusLabel: string
  /**
   * 生​命​值
   */
  statHealth: string
  /**
   * 士​气
   */
  statMorale: string
  /**
   * 领​导​力
   */
  statLeadership: string
  /**
   * 潜​行
   */
  statStealth: string
  /**
   * 背​包
   */
  inventoryLabel: string
  /**
   * 身​无​长​物​。
   */
  nothingCarried: string
  /**
   * T​-​{​h​o​u​r​s​}​小​时​ ​—​ ​爆​发​前
   * @param {number} hours
   */
  timeBeforeOutbreak: RequiredParams<'hours'>
  /**
   * 第​一​天​ ​—​ ​零​时​刻
   */
  timeHourZero: string
  /**
   * 第​{​d​a​y​s​}​天
   * @param {number} days
   */
  timeDay: RequiredParams<'days'>
  /**
   * 坏​结​局
   */
  endingTypeBad: string
  /**
   * 中​立​结​局
   */
  endingTypeNeutral: string
  /**
   * 好​结​局
   */
  endingTypeGood: string
  /**
   * 隐​藏​结​局
   */
  endingTypeSecret: string
  /**
   * 找​不​到​结​局​数​据​。
   */
  noEndingData: string
  /**
   * 返​回​主​界​面
   */
  returnToTitle: string
  /**
   * 再​玩​一​次
   */
  playAgain: string
  /**
   * 做​出​的​选​择​：​{​c​o​u​n​t​}
   * @param {number} count
   */
  choicesMade: RequiredParams<'count'>
  /**
   * 访​问​的​场​景​：​{​c​o​u​n​t​}
   * @param {number} count
   */
  scenesVisited: RequiredParams<'count'>
}

export type TranslationFunctions = {
  /**
   * — 文字冒险游戏 —
   */
  tagline: () => LocalizedString
  /**
   * 在一切改变前的48小时。
   */
  gameSubtitle: () => LocalizedString
  /**
   * 新游戏
   */
  newGame: () => LocalizedString
  /**
   * 继续
   */
  continue: () => LocalizedString
  /**
   * v0.1.0 — 独立作品
   */
  versionLabel: () => LocalizedString
  /**
   * 载入中...
   */
  loading: () => LocalizedString
  /**
   * 正在载入场景…
   */
  loadingScene: () => LocalizedString
  /**
   * 关闭
   */
  dismiss: () => LocalizedString
  /**
   * 你的选择
   */
  yourMove: () => LocalizedString
  /**
   * 条件不满足
   */
  requirementsNotMet: () => LocalizedString
  /**
   * 状态
   */
  statusLabel: () => LocalizedString
  /**
   * 生命值
   */
  statHealth: () => LocalizedString
  /**
   * 士气
   */
  statMorale: () => LocalizedString
  /**
   * 领导力
   */
  statLeadership: () => LocalizedString
  /**
   * 潜行
   */
  statStealth: () => LocalizedString
  /**
   * 背包
   */
  inventoryLabel: () => LocalizedString
  /**
   * 身无长物。
   */
  nothingCarried: () => LocalizedString
  /**
   * T-{hours}小时 — 爆发前
   */
  timeBeforeOutbreak: (arg: { hours: number }) => LocalizedString
  /**
   * 第一天 — 零时刻
   */
  timeHourZero: () => LocalizedString
  /**
   * 第{days}天
   */
  timeDay: (arg: { days: number }) => LocalizedString
  /**
   * 坏结局
   */
  endingTypeBad: () => LocalizedString
  /**
   * 中立结局
   */
  endingTypeNeutral: () => LocalizedString
  /**
   * 好结局
   */
  endingTypeGood: () => LocalizedString
  /**
   * 隐藏结局
   */
  endingTypeSecret: () => LocalizedString
  /**
   * 找不到结局数据。
   */
  noEndingData: () => LocalizedString
  /**
   * 返回主界面
   */
  returnToTitle: () => LocalizedString
  /**
   * 再玩一次
   */
  playAgain: () => LocalizedString
  /**
   * 做出的选择：{count}
   */
  choicesMade: (arg: { count: number }) => LocalizedString
  /**
   * 访问的场景：{count}
   */
  scenesVisited: (arg: { count: number }) => LocalizedString
}

export type Formatters = {}
