// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales = 'en' | 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  ui: {
    /**
     * 载​入​中​…
     */
    loading: string
    /**
     * 发​生​错​误
     */
    error: string
    /**
     * 关​闭
     */
    dismiss: string
    /**
     * 返​回
     */
    back: string
    /**
     * 确​认
     */
    confirm: string
    /**
     * 取​消
     */
    cancel: string
    /**
     * 继​续​ ​→
     */
    continue: string
  }
  title: {
    /**
     * 一​个​文​字​冒​险​游​戏
     */
    tagline: string
    /**
     * 一​切​改​变​的​前​四​十​八​小​时​。
     */
    subtitle: string
    /**
     * 开​始​新​游​戏
     */
    newGame: string
    /**
     * 继​续​游​戏
     */
    continue: string
    /**
     * v​{​v​e​r​s​i​o​n​}​ ​—​ ​独​立​开​发
     * @param {string} version
     */
    version: RequiredParams<'version'>
  }
  game: {
    /**
     * 你​的​选​择
     */
    yourMove: string
    /**
     * 场​景​载​入​中​…
     */
    loadingScene: string
    /**
     * 需​要​{​h​i​n​t​}
     * @param {string} hint
     */
    requiresHint: RequiredParams<'hint'>
    /**
     * 已​自​动​存​档
     */
    autoSaved: string
    crisis: {
      /**
       * 时​间​到​了​。​外​面​的​声​音​变​了​。
       */
      timeExpired: string
      /**
       * 防​御​正​在​失​效​。​他​们​正​在​渗​透​进​来​。
       */
      breachImminent: string
      /**
       * 基​地​已​被​攻​陷​。
       */
      baseOverrun: string
      /**
       * 某​些​东​西​改​变​了​。​你​还​说​不​清​楚​是​什​么​。
       */
      awakening: string
    }
  }
  time: {
    /**
     * T​-​{​h​o​u​r​s​}​小​时​ ​—​ ​爆​发​前
     * @param {number} hours
     */
    beforeOutbreak: RequiredParams<'hours'>
    /**
     * 第​一​天​ ​—​ ​零​时
     */
    dayOne: string
    /**
     * 第​{​d​a​y​}​天
     * @param {number} day
     */
    day: RequiredParams<'day'>
  }
  countdown: {
    /**
     * 剩​余​时​间
     */
    label: string
    /**
     * 幸​存​时​长
     */
    labelElapsed: string
    /**
     * {​h​o​u​r​s​}​小​时
     * @param {number} hours
     */
    hours: RequiredParams<'hours'>
    /**
     * —​—
     */
    expired: string
    /**
     * 第​{​d​a​y​}​天
     * @param {number} day
     */
    day: RequiredParams<'day'>
    urgency: {
      safe: string
      /**
       * 时​间​不​多
       */
      warning: string
      /**
       * 危​急
       */
      critical: string
      /**
       * 危​机​已​至
       */
      expired: string
    }
  }
  security: {
    /**
     * 防​御​指​数
     */
    label: string
    level: {
      /**
       * 不​设​防
       */
      none: string
      /**
       * 基​础​加​固
       */
      basic: string
      /**
       * 相​当​安​全
       */
      solid: string
      /**
       * 加​固
       */
      reinforced: string
      /**
       * 安​全
       */
      secure: string
      /**
       * 钢​铁​要​塞
       */
      fortress: string
    }
  }
  hint: {
    infection: {
      /**
       * 右​手​中​指​隐​约​有​些​不​对​劲​，​说​不​上​来​是​什​么​。
       */
      subtle: string
      /**
       * 皮​下​那​种​感​觉​越​来​越​难​以​忽​视​。​不​是​疼​，​是​别​的​什​么​。
       */
      noticeable: string
      /**
       * 某​些​念​头​出​现​的​方​式​让​你​感​到​陌​生​。​你​花​了​更​长​时​间​才​把​它​们​压​下​去​。
       */
      alarming: string
      /**
       * 转​化​几​乎​完​成​。​你​正​在​失​去​自​己​。
       */
      impending: string
      /**
       * 边​界​在​模​糊​。​你​已​经​不​确​定​，​某​些​念​头​，​是​不​是​你​自​己​的​。
       */
      critical: string
    }
    will: {
      /**
       * 你​的​感​知​正​在​改​变​。​但​你​依​然​是​你​。
       */
      awakening: string
      /**
       * 你​开​始​不​确​定​自​己​到​底​想​要​什​么​。
       */
      collapse: string
    }
  }
  statSignal: {
    infection: {
      /**
       * 潜​伏​中
       */
      dormant: string
      /**
       * 活​跃​中
       */
      active: string
      /**
       * 变​异​中
       */
      mutating: string
      /**
       * 扩​散​中
       */
      spreading: string
      /**
       * 异​变​临​界
       */
      critical: string
    }
    will: {
      /**
       * 觉​醒​临​界
       */
      awakening: string
      /**
       * 濒​临​崩​溃
       */
      collapse: string
    }
    trust: {
      /**
       * 信​任​·​不​稳​定
       */
      unstable: string
      /**
       * 信​任​·​崩​溃​临​界
       */
      critical: string
    }
    leadership: {
      /**
       * 领​导​力​·​初​具​威​信
       */
      established: string
      /**
       * 领​导​力​·​核​心​支​柱
       */
      pillar: string
      /**
       * 领​导​力​·​不​可​或​缺
       */
      indispensable: string
    }
  }
  stats: {
    /**
     * 状​态
     */
    label: string
    /**
     * 生​命​值
     */
    health: string
    /**
     * 士​气
     */
    morale: string
    /**
     * 领​导​力
     */
    leadership: string
    /**
     * 潜​行
     */
    stealth: string
    /**
     * 资​金
     */
    money: string
    /**
     * 信​任
     */
    trust: string
  }
  inventory: {
    /**
     * 背​包
     */
    label: string
    /**
     * 身​无​长​物​。
     */
    empty: string
    /**
     * ×​{​q​t​y​}
     * @param {number} qty
     */
    quantity: RequiredParams<'qty'>
    /**
     * 使​用
     */
    use: string
    /**
     * 工​作​台
     */
    workshop: string
    /**
     * 配​方
     */
    recipes: string
    /**
     * 材​料
     */
    materials: string
  }
  journal: {
    /**
     * 日​记
     */
    label: string
    /**
     * 第​{​d​a​y​}​天
     * @param {number} day
     */
    day: RequiredParams<'day'>
    /**
     * 你​还​没​有​写​下​任​何​东​西​。
     */
    empty: string
    /**
     * 展​开
     */
    toggle: string
  }
  ending: {
    type: {
      /**
       * 坏​结​局
       */
      bad: string
      /**
       * 普​通​结​局
       */
      neutral: string
      /**
       * 好​结​局
       */
      good: string
      /**
       * 隐​藏​结​局
       */
      secret: string
    }
    /**
     * 选​择​次​数​：​{​c​o​u​n​t​}
     * @param {number} count
     */
    choicesMade: RequiredParams<'count'>
    /**
     * 访​问​场​景​：​{​c​o​u​n​t​}
     * @param {number} count
     */
    scenesVisited: RequiredParams<'count'>
    /**
     * 日​记
     */
    journal: string
    /**
     * 日​记​条​目
     */
    journalEntries: string
    /**
     * 暂​无​条​目​。
     */
    journalEmpty: string
    /**
     * 裴​嘉​应​的​笔​记​本
     */
    peiNotebook: string
    /**
     * 有​新​条​目​可​用​！
     */
    peiNotebookNewEntry: string
    /**
     * 超​频
     */
    overclock: string
    /**
     * 异​化​视​角
     */
    depravedInsight: string
    /**
     * 再​玩​一​次
     */
    playAgain: string
    /**
     * 返​回​主​菜​单
     */
    returnToTitle: string
    /**
     * 未​找​到​结​局​数​据​。
     */
    noData: string
  }
  save: {
    /**
     * 存​档​ ​{​s​l​o​t​}
     * @param {number} slot
     */
    slot: RequiredParams<'slot'>
    /**
     * 空​存​档
     */
    empty: string
    /**
     * 存​档​于​ ​{​d​a​t​e​}
     * @param {string} date
     */
    savedAt: RequiredParams<'date'>
  }
  achievements: {
    /**
     * 成​就
     */
    label: string
    /**
     * 已​解​锁​：​{​t​i​t​l​e​}
     * @param {string} title
     */
    unlocked: RequiredParams<'title'>
    /**
     * ?​?​?
     */
    secret: string
  }
  errors: {
    /**
     * 找​不​到​场​景​：​{​i​d​}
     * @param {string} id
     */
    sceneNotFound: RequiredParams<'id'>
    /**
     * 存​档​ ​{​s​l​o​t​}​ ​不​存​在​。
     * @param {number} slot
     */
    saveNotFound: RequiredParams<'slot'>
    /**
     * 该​选​项​目​前​不​可​用​。
     */
    choiceUnavailable: string
    /**
     * 未​载​入​游​戏​。
     */
    noGameLoaded: string
  }
}

export type TranslationFunctions = {
  ui: {
    /**
     * 载入中…
     */
    loading: () => LocalizedString
    /**
     * 发生错误
     */
    error: () => LocalizedString
    /**
     * 关闭
     */
    dismiss: () => LocalizedString
    /**
     * 返回
     */
    back: () => LocalizedString
    /**
     * 确认
     */
    confirm: () => LocalizedString
    /**
     * 取消
     */
    cancel: () => LocalizedString
    /**
     * 继续 →
     */
    continue: () => LocalizedString
  }
  title: {
    /**
     * 一个文字冒险游戏
     */
    tagline: () => LocalizedString
    /**
     * 一切改变的前四十八小时。
     */
    subtitle: () => LocalizedString
    /**
     * 开始新游戏
     */
    newGame: () => LocalizedString
    /**
     * 继续游戏
     */
    continue: () => LocalizedString
    /**
     * v{version} — 独立开发
     */
    version: (arg: { version: string }) => LocalizedString
  }
  game: {
    /**
     * 你的选择
     */
    yourMove: () => LocalizedString
    /**
     * 场景载入中…
     */
    loadingScene: () => LocalizedString
    /**
     * 需要{hint}
     */
    requiresHint: (arg: { hint: string }) => LocalizedString
    /**
     * 已自动存档
     */
    autoSaved: () => LocalizedString
    crisis: {
      /**
       * 时间到了。外面的声音变了。
       */
      timeExpired: () => LocalizedString
      /**
       * 防御正在失效。他们正在渗透进来。
       */
      breachImminent: () => LocalizedString
      /**
       * 基地已被攻陷。
       */
      baseOverrun: () => LocalizedString
      /**
       * 某些东西改变了。你还说不清楚是什么。
       */
      awakening: () => LocalizedString
    }
  }
  time: {
    /**
     * T-{hours}小时 — 爆发前
     */
    beforeOutbreak: (arg: { hours: number }) => LocalizedString
    /**
     * 第一天 — 零时
     */
    dayOne: () => LocalizedString
    /**
     * 第{day}天
     */
    day: (arg: { day: number }) => LocalizedString
  }
  countdown: {
    /**
     * 剩余时间
     */
    label: () => LocalizedString
    /**
     * 幸存时长
     */
    labelElapsed: () => LocalizedString
    /**
     * {hours}小时
     */
    hours: (arg: { hours: number }) => LocalizedString
    /**
     * ——
     */
    expired: () => LocalizedString
    /**
     * 第{day}天
     */
    day: (arg: { day: number }) => LocalizedString
    urgency: {
      safe: () => LocalizedString
      /**
       * 时间不多
       */
      warning: () => LocalizedString
      /**
       * 危急
       */
      critical: () => LocalizedString
      /**
       * 危机已至
       */
      expired: () => LocalizedString
    }
  }
  security: {
    /**
     * 防御指数
     */
    label: () => LocalizedString
    level: {
      /**
       * 不设防
       */
      none: () => LocalizedString
      /**
       * 基础加固
       */
      basic: () => LocalizedString
      /**
       * 相当安全
       */
      solid: () => LocalizedString
      /**
       * 加固
       */
      reinforced: () => LocalizedString
      /**
       * 安全
       */
      secure: () => LocalizedString
      /**
       * 钢铁要塞
       */
      fortress: () => LocalizedString
    }
  }
  hint: {
    infection: {
      /**
       * 右手中指隐约有些不对劲，说不上来是什么。
       */
      subtle: () => LocalizedString
      /**
       * 皮下那种感觉越来越难以忽视。不是疼，是别的什么。
       */
      noticeable: () => LocalizedString
      /**
       * 某些念头出现的方式让你感到陌生。你花了更长时间才把它们压下去。
       */
      alarming: () => LocalizedString
      /**
       * 转化几乎完成。你正在失去自己。
       */
      impending: () => LocalizedString
      /**
       * 边界在模糊。你已经不确定，某些念头，是不是你自己的。
       */
      critical: () => LocalizedString
    }
    will: {
      /**
       * 你的感知正在改变。但你依然是你。
       */
      awakening: () => LocalizedString
      /**
       * 你开始不确定自己到底想要什么。
       */
      collapse: () => LocalizedString
    }
  }
  statSignal: {
    infection: {
      /**
       * 潜伏中
       */
      dormant: () => LocalizedString
      /**
       * 活跃中
       */
      active: () => LocalizedString
      /**
       * 变异中
       */
      mutating: () => LocalizedString
      /**
       * 扩散中
       */
      spreading: () => LocalizedString
      /**
       * 异变临界
       */
      critical: () => LocalizedString
    }
    will: {
      /**
       * 觉醒临界
       */
      awakening: () => LocalizedString
      /**
       * 濒临崩溃
       */
      collapse: () => LocalizedString
    }
    trust: {
      /**
       * 信任·不稳定
       */
      unstable: () => LocalizedString
      /**
       * 信任·崩溃临界
       */
      critical: () => LocalizedString
    }
    leadership: {
      /**
       * 领导力·初具威信
       */
      established: () => LocalizedString
      /**
       * 领导力·核心支柱
       */
      pillar: () => LocalizedString
      /**
       * 领导力·不可或缺
       */
      indispensable: () => LocalizedString
    }
  }
  stats: {
    /**
     * 状态
     */
    label: () => LocalizedString
    /**
     * 生命值
     */
    health: () => LocalizedString
    /**
     * 士气
     */
    morale: () => LocalizedString
    /**
     * 领导力
     */
    leadership: () => LocalizedString
    /**
     * 潜行
     */
    stealth: () => LocalizedString
    /**
     * 资金
     */
    money: () => LocalizedString
    /**
     * 信任
     */
    trust: () => LocalizedString
  }
  inventory: {
    /**
     * 背包
     */
    label: () => LocalizedString
    /**
     * 身无长物。
     */
    empty: () => LocalizedString
    /**
     * ×{qty}
     */
    quantity: (arg: { qty: number }) => LocalizedString
    /**
     * 使用
     */
    use: () => LocalizedString
    /**
     * 工作台
     */
    workshop: () => LocalizedString
    /**
     * 配方
     */
    recipes: () => LocalizedString
    /**
     * 材料
     */
    materials: () => LocalizedString
  }
  journal: {
    /**
     * 日记
     */
    label: () => LocalizedString
    /**
     * 第{day}天
     */
    day: (arg: { day: number }) => LocalizedString
    /**
     * 你还没有写下任何东西。
     */
    empty: () => LocalizedString
    /**
     * 展开
     */
    toggle: () => LocalizedString
  }
  ending: {
    type: {
      /**
       * 坏结局
       */
      bad: () => LocalizedString
      /**
       * 普通结局
       */
      neutral: () => LocalizedString
      /**
       * 好结局
       */
      good: () => LocalizedString
      /**
       * 隐藏结局
       */
      secret: () => LocalizedString
    }
    /**
     * 选择次数：{count}
     */
    choicesMade: (arg: { count: number }) => LocalizedString
    /**
     * 访问场景：{count}
     */
    scenesVisited: (arg: { count: number }) => LocalizedString
    /**
     * 日记
     */
    journal: () => LocalizedString
    /**
     * 日记条目
     */
    journalEntries: () => LocalizedString
    /**
     * 暂无条目。
     */
    journalEmpty: () => LocalizedString
    /**
     * 裴嘉应的笔记本
     */
    peiNotebook: () => LocalizedString
    /**
     * 有新条目可用！
     */
    peiNotebookNewEntry: () => LocalizedString
    /**
     * 超频
     */
    overclock: () => LocalizedString
    /**
     * 异化视角
     */
    depravedInsight: () => LocalizedString
    /**
     * 再玩一次
     */
    playAgain: () => LocalizedString
    /**
     * 返回主菜单
     */
    returnToTitle: () => LocalizedString
    /**
     * 未找到结局数据。
     */
    noData: () => LocalizedString
  }
  save: {
    /**
     * 存档 {slot}
     */
    slot: (arg: { slot: number }) => LocalizedString
    /**
     * 空存档
     */
    empty: () => LocalizedString
    /**
     * 存档于 {date}
     */
    savedAt: (arg: { date: string }) => LocalizedString
  }
  achievements: {
    /**
     * 成就
     */
    label: () => LocalizedString
    /**
     * 已解锁：{title}
     */
    unlocked: (arg: { title: string }) => LocalizedString
    /**
     * ???
     */
    secret: () => LocalizedString
  }
  errors: {
    /**
     * 找不到场景：{id}
     */
    sceneNotFound: (arg: { id: string }) => LocalizedString
    /**
     * 存档 {slot} 不存在。
     */
    saveNotFound: (arg: { slot: number }) => LocalizedString
    /**
     * 该选项目前不可用。
     */
    choiceUnavailable: () => LocalizedString
    /**
     * 未载入游戏。
     */
    noGameLoaded: () => LocalizedString
  }
}

export type Formatters = {}
